app = 'soilprobe-api-floral-sound-9539'
primary_region = 'gru'

[build]
  dockerfile = "api/Dockerfile"

[env]
  ENV = "prod"
  LOG_LEVEL = "INFO"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1

[deploy]
  release_command = "alembic upgrade head"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1